# Permalinks
permalink:        pretty

# Setup
title:            Atharva Vaidya
tagline:          
url:              http://atharva.me
paginate:         1
baseurl:          /
author:
  name:           Atharva Vaidya
  url:            https://twitter.com/atharva_vaidya
  email:          atharva.vaidya@drexel.edu

# Custom vars
version:          1.0.0
pages_list:  
  About: '/about'     
  Projects: '/projects'
  Archive: '/archive'
  Feed: '/feed.xml'
